<a href="https://colab.research.google.com/github/subhaganesh/deep_learning_repo/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#In this notebook we are  going to cover some of the most fundamental concepts of tensors using tensorflow

More specifically , we're going to cover:

*introduction to tensors

*getting information from tensors

*manipulating tensors

*tensors & numpy

*using GPU'S with tensorflow or (TPU'S)

*using @tf.function (a way to speed up your regular python functions)

*exercises to try for yourself!  

![picture](https://drive.google.com/file/d/1ktimUdBWompnTnV2sfw5X44QtiiKGlTU/view?usp=drive_link)

#**Introduction to tensors**

In [ ]:
#import tensorflow
import tensorflow as tf
print(tf.__version__)

2.13.0


In [ ]:
#create tensors with tf.constant ()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#check the number of dimensions of a tensor (ndim stands for number of dimensions)

#check the dimension for scalar
scalar.ndim

0

In [ ]:
#create a vector

vector=tf.constant([10,2])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  2], dtype=int32)>

In [ ]:
#check the dimension of vector
vector.ndim

1

In [ ]:
#create a matrix (has more then one dimension)
matrix= tf.constant([[10,5],
                     [1,2]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  5],
       [ 1,  2]], dtype=int32)>

In [ ]:
#check the dimension of matrix
matrix.ndim


2

In [ ]:
#create another matrix
another_matrix= tf.constant([[10.,7.],
                            [3.,2.],
                            [3.,3.]],dtype=tf.float16) #specify the data type with dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 3.,  3.]], dtype=float16)>

In [ ]:
#check the dimension of matrix
another_matrix.ndim

2

In [ ]:
# let's create a tensor
tensor= tf.constant([[[1,2,3],
                      [4,5,6]],
                     [[7,8,9],
                      [10,11,12]],
                     [[13,14,15],
                      [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

what we've created so far:

*scalar: a single number

*vector: a number with direction (e.g wind speed and direction)

*matrix: a 2-dimentional array of numbers

*tensor: an n- dimensional array of numbers.  (when n can be any number, a 0-dimensional tensor is a scalar ,a 1-dimensional tensor is a vector,a 2-dimensional tensor is a matrix,a 3-dimensional tensor is a n-dimensional matrix)


#creating tensors with tf.**Variable**

In [ ]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [ ]:
# create the same tensor with tf.variable() as above tf.constant

changeable_tensor = tf.Variable([1,2])
unchangeable_tensor=tf.constant([1,2])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>)

let's try change one of the elements in our changeable tensor

changeable_tensor[0]=7
changeable_tensor

To change an element of a tf.Variable() tensor requires the assign() method.

In [ ]:
#how about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 2], dtype=int32)>

let's try change our unchangable tensor
 Will error (can't change tf.constant())
unchangeable_tensor[0].assign(3)
unchangeable_tensor

Which one should you use? tf.constant() or tf.Variable()?

It will depend on what your problem requires. However, most of the time, TensorFlow will automatically choose for you (when loading data or modelling data).

#creating random tensors

Random tensors are tensors of some abitrary size which contain random numbers.

In [ ]:
#create two random (but the same ) tensors

random_1 = tf.random.Generator.from_seed(22)  #set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7531523 ,  2.0261486 ],
       [-0.06997604,  0.8544515 ],
       [ 0.11754749,  0.03493892]], dtype=float32)>

In [ ]:

random_2 = tf.random.Generator.from_seed(22)  #set seed for reproducibility
random_2 = random_2.normal(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7531523 ,  2.0261486 ],
       [-0.06997604,  0.8544515 ],
       [ 0.11754749,  0.03493892]], dtype=float32)>

In [ ]:
#are they equal?
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

The random_1 and random_2 are equal because it has same  random seed if it does n't have same random seed it won't give same value .this rule is apt for both uniform and normal

In [ ]:
random_3 = tf.random.Generator.from_seed(42)  #set seed for reproducibility
random_3 = random_3.uniform(shape=(3,2))
random_3

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.7493447 , 0.73561966],
       [0.45230794, 0.49039817],
       [0.1889317 , 0.52027524]], dtype=float32)>

In [ ]:
random_4 = tf.random.Generator.from_seed(42)  #set seed for reproducibility
random_4 = random_4.uniform(shape=(3,2))
random_4

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.7493447 , 0.73561966],
       [0.45230794, 0.49039817],
       [0.1889317 , 0.52027524]], dtype=float32)>

In [ ]:
random_3 == random_4

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [ ]:
uniform=tf.random.uniform(shape=(2,2)),
normal=tf.random.normal(shape=(2,2))
uniform,normal

((<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
  array([[0.15907753, 0.00838828],
         [0.6158956 , 0.87907624]], dtype=float32)>,),
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-0.1542775 ,  0.744887  ],
        [-0.70548195, -0.7847715 ]], dtype=float32)>)

#shuffle the order of elements in a tensor

What if you wanted to shuffle the order of a tensor?

Wait, why would you want to do that?

Let's say you working with 15,000 images of cats and dogs and the first 10,000 images of were of cats and the next 5,000 were of dogs. This order could effect how a neural network learns (it may overfit by learning the order of the data), instead, it might be a good idea to move your data around.

In [ ]:
# Shuffle a tensor (valuable for when you want to shuffle your data)
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
# Gets different results each time
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
#shuffle our non-shuffled tensor with random seed
tf.random.shuffle(not_shuffled, seed=42) #---operation level seed

# the values are changing because it has no global level seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [ ]:
 #the values will not change because of global level seed

tf.random.set_seed(42)                   #---global level seed
tf.random.shuffle(not_shuffled, seed=42) #---operation level seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

#other ways to make tensors

In [ ]:
#create tensor of all ones
tf.ones([5,4])

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [ ]:
#create tensor of all zeros
tf.zeros(shape=(3,4) )

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

the main difference between numpy arrays and tensorflow tensors is that tensors can be run on a gpu(much faster for numerical computing).

In [ ]:
#you can also turn numpy arrays into tensors
import numpy as np
numpy_A= np.arange(1,25,dtype=np.int32) #create a numpy array between 1 & 25
numpy_A

# x = tf.constant(some_matrix) #capital for matrix or tensor
# y = tf.constant(vector) # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant (numpy_A, shape=(2,3,4))
B = tf.constant (numpy_A) # note: the shape total (2*4*3) has to match the number of elements in the array
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [ ]:
A.ndim

3

#getting information from tensors


 when dealing with tensors you probably want to be aware of the following
 attributes:
* shape  
* rank
* axis or dimension
* size   



In [ ]:
#create a rank 4 tensor (4 dimensions)

rank_4_tensor = tf.zeros(shape=([2,3,4,5]))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape,  rank_4_tensor.ndim,  tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
rank_4_tensor.shape[0]

2

In [ ]:
rank_4_tensor[0, :2]

<tf.Tensor: shape=(2, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
# Get various attributes of tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor))
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy()) # .numpy() converts to NumPy array


Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): tf.Tensor(120, shape=(), dtype=int32)
Total number of elements (2*3*4*5): 120


#indexing and expanding tensors
 index tensors just like Python lists.

In [ ]:
#get the first 2 elements of each dimension

rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [ ]:
# Get the first element from each dimension  except for the final one
rank_4_tensor[:1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Get the first element from each dimension  except for the third one
rank_4_tensor[:1, :1, : , :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [ ]:
#create a rank 2 tensor (2dimensions)
rank_2_tensor = tf.constant([[10,7],
                             [3,4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [ ]:
# Get the last item of each row
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
# Add an extra dimension (to the end)
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # in Python "..." means "all dimensions prior to"
rank_2_tensor, rank_3_tensor # shape (2, 2), shape (2, 2, 1)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 7]],
 
        [[ 3],
         [ 4]]], dtype=int32)>)

In [ ]:
#You can achieve the same using tf.expand_dims()

tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means last axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

#Manipulating tensors (tensor operations)
##Basic operation

* addition   
* subtraction
* multiplication
* divide



In [ ]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

Since we used tf.constant(), the original tensor is unchanged (the addition gets done on a copy).

In [ ]:
# Original tensor unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# Multiplication (known as element-wise multiplication)
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
# Subtraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

You can also use the equivalent TensorFlow function. Using the TensorFlow function (where possible) has the advantage of being speed up later down the line when running as part of a TensorFlow graph.

In [ ]:
# Use the tensorflow function equivalent of the '*' (multiply) operator
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
x=tf.constant([[1,2],
               [3,4]])
y=tf.constant([[2,3],
               [3,4]])
tf.add(x,y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 5],
       [6, 8]], dtype=int32)>

In [ ]:
tf.subtract(x,y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-1, -1],
       [ 0,  0]], dtype=int32)>

In [ ]:
tf.divide(x,y)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.5       , 0.66666667],
       [1.        , 1.        ]])>

In [ ]:
# The original tensor is still unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

#Matrix mutliplication

One of the most common operations in machine learning algorithms is matrix multiplication.

TensorFlow implements this matrix multiplication functionality in the tf.matmul() method.

The main two rules for matrix multiplication to remember are:

The inner dimensions must match:

(3, 5) @ (3, 5) won't work

(5, 3) @ (3, 5) will work

(3, 5) @ (5, 3) will work

The resulting matrix has the shape of the outer dimensions:

(5, 3) @ (3, 5) -> (5, 5)

(3, 5) @ (5, 3) -> (3, 3)

🔑 Note: '@' in Python is the symbol for matrix multiplication.

In [ ]:
# Matrix multiplication in TensorFlow
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
# Matrix multiplication with Python operator '@'
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
# Create (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

 Try to matrix multiply them (will error)
X @ Y

Trying to matrix multiply two tensors with the shape (3, 2) errors because the inner dimensions don't match.

We need to either:

Reshape X to (2, 3) so it's (2, 3) @ (3, 2).

Reshape Y to (3, 2) so it's (3, 2) @ (2, 3).

We can do this with either:

tf.reshape() - allows us to reshape a tensor into a defined shape.

tf.transpose() - switches the dimensions of a given tensor.

In [ ]:
# Example of reshape (3, 2) -> (2, 3)
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
# Try matrix multiplication with reshaped Y
X @ tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

It worked, let's try the same with a reshaped X, except this time we'll use tf.transpose() and tf.matmul()

In [ ]:
# Example of transpose (3, 2) -> (2, 3)
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [ ]:
# Try matrix multiplication
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
# You can achieve the same result with parameters
tf.matmul(a=X, b=Y, transpose_a=True, transpose_b=False)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

This kind of data manipulation is a reminder: you'll spend a lot of your time in machine learning and working with neural networks reshaping data (in the form of tensors) to prepare it to be used with various operations (such as feeding it to a model).

# The dot product



Multiplying matrices by eachother is also referred to as the dot product.

You can perform the tf.matmul() operation using tf.tensordot().

In [ ]:
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

tensordot(transpose)

In [ ]:
# Perform the dot product on X and Y (requires X to be transposed)
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
tf.tensordot(X, tf.transpose(Y), axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

tensordot(reshape)

In [ ]:
tf.tensordot(tf.reshape(X, (2,3)), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [ ]:
tf.tensordot(X,tf.reshape(Y, (2,3)),axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

matmul(transpose)

In [ ]:
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
X, Y,  tf.matmul(X, tf.transpose(Y))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]], dtype=int32)>)

matmul(reshape)

In [ ]:
# Perform matrix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, (2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
tf.matmul(tf.reshape(X, (2,3)), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

Hmm... they result in different values.

Which is strange because when dealing with Y (a (3x2) matrix), reshaping to (2, 3) and tranposing it result in the same shape.

In [ ]:
# Check shapes of Y, reshaped Y and tranposed Y
Y.shape, tf.reshape(Y, (2, 3)).shape, tf.transpose(Y).shape

(TensorShape([3, 2]), TensorShape([2, 3]), TensorShape([2, 3]))

But calling tf.reshape() and tf.transpose() on Y don't necessarily result in the same values.

In [ ]:
# Check values of Y, reshape Y and tranposed Y
print("Normal Y:")
print(Y, "\n") # "\n" for newline

print("Y reshaped to (2, 3):")
print(tf.reshape(Y, (2, 3)), "\n")

print("Y transposed:")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2, 3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


#Changing the datatype of a tensor

Sometimes you'll want to alter the default datatype of your tensor.

This is common when you want to compute using less precision (e.g. 16-bit floating point numbers vs. 32-bit floating point numbers).

Computing with less precision is useful on devices with less computing capacity such as mobile devices (because the less bits, the less space the computations require).

You can change the datatype of a tensor using tf.cast().

In [ ]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])

# Create a new tensor with default datatype (int32)
C = tf.constant([1, 7])
B, C

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7], dtype=int32)>)

In [ ]:
# Change from float32 to float16 (reduced precision)
B = tf.cast(B, dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [ ]:
# Change from int32 to float32
C = tf.cast(C, dtype=tf.float32)
C

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 7.], dtype=float32)>

#Getting the absolute value


Sometimes you'll want the absolute values (all values are positive) of elements in your tensors.

To do so, you can use tf.abs()

In [ ]:
# Create tensor with negative values
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
# Get the absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

#Finding the min, max, mean, sum (aggregation)


You can quickly aggregate (perform a calculation on a whole tensor) tensors to find things like the minimum value, maximum value, mean and sum of all the elements.

To do so, aggregation methods typically have the syntax reduce()_[action], such as:

*tf.reduce_min() - find the minimum value in a tensor.

*tf.reduce_max() - find the maximum value in a tensor (helpful for when you want to find the highest prediction probability).

*tf.reduce_mean() - find the mean of all elements in a tensor.

*tf.reduce_sum() - find the sum of all elements in a tensor.

Note: typically, each of these is under the math module, e.g. tf.math.reduce_min() but you can use the alias tf.reduce_min().

In [ ]:
# Create a tensor with 50 random values between 0 and 100
E = tf.constant(np.random.randint(low=0, high=100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([81, 92, 39, 39, 72, 29, 34, 48, 71,  4, 45, 50, 98, 89, 20, 64, 99,
       68, 98, 87, 28, 89, 97, 33, 30, 75, 72, 58, 68, 41, 80, 84,  5, 34,
       16, 30, 44, 51, 92, 23, 77, 23, 96,  5, 83, 70, 65, 98, 63, 20])>

In [ ]:
# Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=4>

In [ ]:
# Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [ ]:
# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=57>

In [ ]:
# Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2877>

In [ ]:
#Find the standard deviation
E  #--- dtype=int64

E = tf.cast(E, dtype=tf.float32) # Convert to float 32 dtype

tf.math.reduce_std(E)

<tf.Tensor: shape=(), dtype=float32, numpy=28.565859>

In [ ]:
#another method for finding standard deviation using probability
import tensorflow_probability as tfp
tfp.stats.stddev(E)

<tf.Tensor: shape=(), dtype=float32, numpy=28.565859>

In [ ]:
#Find the variance

E  #--- dtype=int64

E= tf.cast(E, dtype=tf.float32) # Convert to float 32 dtype

tf.math.reduce_variance(E)

<tf.Tensor: shape=(), dtype=float32, numpy=816.00836>

In [ ]:
#another method for finding variance using probability
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=float32, numpy=816.00836>

#Finding the positional maximum and minimum


How about finding the position a tensor where the maximum value occurs?

This is helpful when you want to line up your labels (say ['Green', 'Blue', 'Red']) with your prediction probabilities tensor (e.g. [0.98, 0.01, 0.01]).

In this case, the predicted label (the one with the highest prediction probability) would be 'Green'.

You can do the same for the minimum (if required) with the following:

tf.argmax() - find the position of the maximum element in a given tensor.

tf.argmin() - find the position of the minimum element in a given tensor.

In [ ]:
# Create a tensor with 50 values between 0 and 1
tf.random.set_seed(42)
F = tf.constant(np.random.random(50))
F

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.67309835, 0.59111657, 0.44321366, 0.24139286, 0.06447557,
       0.31139707, 0.54124952, 0.46945251, 0.01385656, 0.67228555,
       0.94745117, 0.0243768 , 0.85312928, 0.39715805, 0.85215537,
       0.43179676, 0.91832438, 0.81258183, 0.82981986, 0.89379402,
       0.36935986, 0.77811181, 0.07992664, 0.71413979, 0.57326774,
       0.85129268, 0.79371893, 0.87383776, 0.46591178, 0.69257685,
       0.15367134, 0.35938154, 0.73765835, 0.35840547, 0.68222747,
       0.59750366, 0.53843765, 0.55957084, 0.78826731, 0.26314816,
       0.3913973 , 0.70620072, 0.79571786, 0.13394844, 0.09457309,
       0.32670633, 0.80601748, 0.19113354, 0.55513884, 0.41689093])>

In [ ]:
# Find the maximum element position of F
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=10>

In [ ]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float64, numpy=0.9474511725899176>

In [ ]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float64, numpy=0.9474511725899176>

In [ ]:
#check for equality
assert F[tf.argmax(F)] == tf.reduce_max(F)

In [ ]:
# Find the minimum element position of F
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=8>

In [ ]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float64, numpy=0.013856564527372828>

In [ ]:
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float64, numpy=0.013856564527372828>

In [ ]:
# Find the maximum element position of F
print(f"The maximum value of F is at position: {tf.argmax(F).numpy()}")
print(f"The maximum value of F is: {tf.reduce_max(F).numpy()}")
print(f"Using tf.argmax() to index F, the maximum value of F is: {F[tf.argmax(F)].numpy()}")
print(f"Are the two max values the same (they should be)? {F[tf.argmax(F)].numpy() == tf.reduce_max(F).numpy()}")

The maximum value of F is at position: 10
The maximum value of F is: 0.9474511725899176
Using tf.argmax() to index F, the maximum value of F is: 0.9474511725899176
Are the two max values the same (they should be)? True


#Squeezing a tensor (removing all single dimensions)

If you need to remove single-dimensions from a tensor (dimensions with size 1), you can use tf.squeeze().

tf.squeeze() - remove all dimensions of 1 from a tensor.


In [ ]:
# Create a rank 5 (5 dimensions) tensor of 50 numbers between 0 and 100
tf.random.set_seed(42)
G = tf.constant(np.random.randint(0, 100, 50), shape=(1, 1, 1, 1, 50))
G.shape, G.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [ ]:
# Squeeze tensor G (remove all 1 dimensions)
G_squeezed = tf.squeeze(G)
G_squeezed.shape, G_squeezed.ndim,G_squeezed

(TensorShape([50]),
 1,
 <tf.Tensor: shape=(50,), dtype=int64, numpy=
 array([40, 69, 10, 94, 42, 76, 64, 76, 36, 74, 84,  4, 80, 29, 71, 82, 81,
        99,  3, 43, 23, 12, 66, 38, 77, 72, 50, 66, 53, 28, 39, 84, 79, 34,
        67, 28, 32, 12, 49, 49, 65, 98, 98, 94, 51, 51, 80, 78, 69, 85])>)

#One-hot encoding
If you have a tensor of indicies and would like to one-hot encode it, you can use tf.one_hot().

You should also specify the depth parameter (the level which you want to one-hot encode to).

In [ ]:
# Create a list of indices
some_list = [0, 1, 2, 3]

# One hot encode them
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

You can also specify values for on_value and off_value instead of the default 0 and 1.

In [ ]:
# Specify custom values for on and off encoding
tf.one_hot(some_list, depth=4, on_value="We're live!", off_value="Offline")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b"We're live!", b'Offline', b'Offline', b'Offline'],
       [b'Offline', b"We're live!", b'Offline', b'Offline'],
       [b'Offline', b'Offline', b"We're live!", b'Offline'],
       [b'Offline', b'Offline', b'Offline', b"We're live!"]], dtype=object)>

#Squaring, log, square root

Many other common mathematical operations you'd like to perform at some stage, probably exist.

Let's take a look at:

*tf.square() - get the square of every value in a tensor.

*tf.sqrt() - get the squareroot of every value in a tensor (note: the elements need to be floats or this will error).

*tf.math.log() - get the natural log of every value in a tensor (elements need to floats).

In [ ]:
# Create a new tensor
H = tf.constant(np.arange(1, 10))
H

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [ ]:
# Square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

# Find the squareroot (will error), needs to be non-integer
tf.sqrt(H)

In [ ]:
# Change H to float32
H = tf.cast(H, dtype=tf.float32)
H

<tf.Tensor: shape=(9,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)>

In [ ]:
# Find the square root
tf.sqrt(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
# Find the log (input also needs to be float)
tf.math.log(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

#Manipulating tf.Variable tensors

Tensors created with tf.Variable() can be changed in place using methods such as:

*.assign() - assign a different value to a particular index of a variable tensor.

*.add_assign() - add to an existing value and reassign it at a particular index of a variable tensor.

In [ ]:
# Create a variable tensor
I = tf.Variable(np.arange(0, 5))
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([0, 1, 2, 3, 4])>

In [ ]:
# Assign the final value a new value of 50
I.assign([0, 1, 2, 3, 50])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([ 0,  1,  2,  3, 50])>

In [ ]:
# The change happens in place (the last value is now 50, not 4)
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([ 0,  1,  2,  3, 50])>

In [ ]:
# Add 10 to every element in I
I.assign_add([10, 10, 10, 10, 10])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([10, 11, 12, 13, 60])>

In [ ]:
# Again, the change happens in place
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([10, 11, 12, 13, 60])>

#Tensors and NumPy

We've seen some examples of tensors interact with NumPy arrays, such as, using NumPy arrays to create tensors.

Tensors can also be converted to NumPy arrays using:

*np.array() - pass a tensor to convert to an ndarray (NumPy's main datatype).

*tensor.numpy() - call on a tensor to convert to an ndarray.

*Doing this is helpful as it makes tensors iterable as well as allows us to use any of NumPy's methods on them.


In [ ]:
# Create a tensor from a NumPy array
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
# Convert tensor J to NumPy with np.array()
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
# Convert tensor J to NumPy with .numpy()
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
k=tf.constant([3.])
print(k)
print('******************')
k.numpy()[0]

tf.Tensor([3.], shape=(1,), dtype=float32)
******************


3.0

By default tensors have dtype=float32, where as NumPy arrays have dtype=float64.

This is because neural networks (which are usually built with TensorFlow) can generally work very well with less precision (32-bit rather than 64-bit).

In [ ]:
# Create a tensor from NumPy and from an array
numpy_J = tf.constant(np.array([3., 7., 10.])) # will be float64 (due to NumPy)
tensor_J = tf.constant([3., 7., 10.]) # will be float32 (due to being TensorFlow default)
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

#Using @tf.function
In your TensorFlow adventures, you might come across Python functions which have the decorator @tf.function.

If you aren't sure what Python decorators do, read RealPython's guide on them.

But in short, decorators modify a function in one way or another.

In the @tf.function decorator case, it turns a Python function into a callable TensorFlow graph. Which is a fancy way of saying, if you've written your own Python function, and you decorate it with @tf.function, when you export your code (to potentially run on another device), TensorFlow will attempt to convert it into a fast(er) version of itself (by making it part of a computation graph).


In [ ]:
# Create a simple function
def function(x, y):
  return x ** 2 + y

x = tf.constant(np.arange(0, 10))
y = tf.constant(np.arange(10, 20))
function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [ ]:
# Create the same function and decorate it with tf.function
@tf.function
def tf_function(x, y):
  return x ** 2 + y

tf_function(x, y)


<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

If you noticed no difference between the above two functions (the decorated one and the non-decorated one) you'd be right.

Much of the difference happens behind the scenes. One of the main ones being potential code speed-ups where possible.

#Finding access to GPUs

We've mentioned GPUs plenty of times throughout this notebook.

So how do you check if you've got one available?

You can check if you've got access to a GPU using tf.config.list_physical_devices().

In [ ]:
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


from the above outputs an empty array (or nothing), it means you don't have access to a GPU (or at least TensorFlow can't find it).

If you're running in Google Colab, you can access a GPU by going to Runtime -> Change Runtime Type -> Select GPU (note: after doing this your notebook will restart and any variables you've saved will be lost).

Once you've changed your runtime type, run the cell below

In [ ]:
import tensorflow as tf
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


If you've got access to a GPU, the cell above should output something like:

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

You can also find information about your GPU using !nvidia-smi.

In [ ]:
!nvidia-smi

Mon Sep 18 06:00:48 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   48C    P0    29W /  70W |    361MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

🔑 Note: If you have access to a GPU, TensorFlow will automatically use it whenever possible.

# Excercise

1.Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

2.Find the shape, rank and size of the tensors you created in 1.

3.Create two tensors containing random values between 0 and 1 with shape [5, 300].

4.Multiply the two tensors you created in 3 using matrix multiplication.

5.Multiply the two tensors you created in 3 using dot product.

6.Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

7.Find the min and max values of the tensor you created in 6.

8.Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

9.Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

10.One-hot encode the tensor you created in 9.

In [ ]:
#1.Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

scalar=tf.constant(2.0)    #----------------------0d

vector=tf.constant([1,2,3],dtype=tf.float32) #-----1d

matrix=tf.constant([[1,2,3],
                     [4,5,6]],dtype=tf.float32)   #--------2d

tensor=tf.constant([[[1,2,3],
                     [4,5,6]],

                    [[7,8,9],
                     [10,11,12]]],dtype=tf.float32)   #-----3d

scalar,vector,matrix,tensor

(<tf.Tensor: shape=(), dtype=float32, numpy=2.0>,
 <tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[1., 2., 3.],
        [4., 5., 6.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
 array([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],
 
        [[ 7.,  8.,  9.],
         [10., 11., 12.]]], dtype=float32)>)

In [ ]:
#2.Find the shape, rank and size of the tensors you created in 1.
zero_dimension=scalar.shape, scalar.ndim, tf.size(scalar)

one_dimension=vector.shape,vector.ndim, tf.size(vector)

two_dimension=matrix.shape, matrix.ndim, tf.size(matrix)

three_dimension= tensor.shape, tensor.ndim, tf.size(tensor)

zero_dimension, one_dimension, two_dimension, three_dimension

((TensorShape([]), 0, <tf.Tensor: shape=(), dtype=int32, numpy=1>),
 (TensorShape([3]), 1, <tf.Tensor: shape=(), dtype=int32, numpy=3>),
 (TensorShape([2, 3]), 2, <tf.Tensor: shape=(), dtype=int32, numpy=6>),
 (TensorShape([2, 2, 3]), 3, <tf.Tensor: shape=(), dtype=int32, numpy=12>))

In [ ]:
#3.Create two tensors containing random values between 0 and 1 with shape [5, 300].

random_num_one= tf.random.Generator.from_seed(11)
random_num_one= random_num_one.normal(shape=(5,300))
random_num_one

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[ 0.2730574 , -0.29925638, -0.3652325 , ..., -0.85103077,
         0.8119971 ,  2.0856276 ],
       [ 0.45117483, -0.90232193, -1.5350152 , ..., -0.27568147,
         0.24829084, -0.90035295],
       [-2.2462473 , -0.4587842 , -1.9838426 , ...,  1.3616577 ,
        -0.8285553 , -0.38055852],
       [ 0.43401343, -2.8677838 ,  0.8929652 , ..., -1.273435  ,
        -3.5026186 , -0.79623157],
       [-0.29896575,  1.3008425 ,  0.0544327 , ...,  0.61491543,
        -1.1504325 , -1.4290743 ]], dtype=float32)>

In [ ]:
random_num_two= tf.random.Generator.from_seed(13)
random_num_two= random_num_two.normal(shape=(5,300))
random_num_two

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[ 0.37944326, -0.6664026 ,  0.6054596 , ...,  1.071573  ,
         0.32903498, -0.12147247],
       [-0.81168556,  1.0684562 ,  0.03192343, ...,  0.08420128,
        -0.35761362,  0.529446  ],
       [ 1.0076104 , -1.5559709 , -0.07964771, ..., -1.5163175 ,
        -1.3340821 , -0.34527028],
       [ 1.4093482 ,  0.09789068,  2.083792  , ...,  1.590681  ,
         0.7343326 , -0.7077091 ],
       [-0.8969618 , -1.7225893 ,  1.3476163 , ..., -0.63512534,
        -2.165135  ,  0.54229033]], dtype=float32)>

In [ ]:
#4.Multiply the two tensors you created in 3 using matrix multiplication.

'''The shape was 5*300 and 5*300 it will create error
so we want to reshape this by making one as 300*5
then it will be 5*300 and 300*5 '''

reshaping = tf.reshape(random_num_two,shape=(300,5))

multiply = tf.matmul(random_num_one, reshaping)
multiply


<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 30.366016  ,  -2.5914252 , -37.015476  ,   3.184197  ,
         -5.734166  ],
       [  0.06643558,   1.2047734 , -10.946961  ,  28.278706  ,
         18.7377    ],
       [-16.67557   , -22.900484  , -53.140705  ,  -7.3362727 ,
        -29.866795  ],
       [-22.415352  , -27.029959  ,  12.919829  ,  14.587365  ,
         -3.685363  ],
       [ 36.41489   ,  14.289251  ,  -8.141048  ,  -0.42489052,
         31.994646  ]], dtype=float32)>

In [ ]:
#5.Multiply the two tensors you created in 3 using dot product.
dot_product = tf.tensordot(random_num_one, tf.reshape(random_num_two,shape=(300,5)),axes=1)
dot_product


<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 30.366016  ,  -2.5914252 , -37.015476  ,   3.184197  ,
         -5.734166  ],
       [  0.06643558,   1.2047734 , -10.946961  ,  28.278706  ,
         18.7377    ],
       [-16.67557   , -22.900484  , -53.140705  ,  -7.3362727 ,
        -29.866795  ],
       [-22.415352  , -27.029959  ,  12.919829  ,  14.587365  ,
         -3.685363  ],
       [ 36.41489   ,  14.289251  ,  -8.141048  ,  -0.42489052,
         31.994646  ]], dtype=float32)>

In [ ]:
#6.Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
random_tensor = tf.random.normal(shape=(224, 224, 3))
random_tensor

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[ 0.3274685 , -0.8426258 ,  0.3194337 ],
        [-1.4075519 , -2.3880599 , -1.0392479 ],
        [-0.5573232 ,  0.539707  ,  1.6994323 ],
        ...,
        [-2.1195276 ,  1.8320249 ,  1.1457133 ],
        [ 0.54631245,  1.8743154 ,  0.11950399],
        [-0.29805267, -0.29960835,  1.5552508 ]],

       [[-0.3161619 , -0.72182304, -0.989772  ],
        [ 1.1060055 , -0.21110982, -0.47060865],
        [ 0.07136566, -0.48230812, -1.2975956 ],
        ...,
        [ 0.10062912,  0.38567653, -0.1904147 ],
        [-1.1275961 ,  0.64350545,  1.1970826 ],
        [-0.37379304,  0.23610258, -0.13297646]],

       [[ 1.3060379 ,  0.26648018, -0.07864442],
        [-1.114526  , -0.595572  ,  0.7152307 ],
        [ 1.2495805 ,  0.38960335, -0.5431543 ],
        ...,
        [ 1.6160519 ,  0.8865264 ,  1.0241655 ],
        [ 0.26582795,  0.82782304, -0.27606866],
        [ 1.8379737 , -0.24267256,  0.6261893 ]],

       ...,

     

In [ ]:
#7.Find the min and max values of the tensor you created in 6.
min=tf.reduce_min(random_tensor)
max=tf.reduce_max(random_tensor)

min,max

(<tf.Tensor: shape=(), dtype=float32, numpy=-5.4462285>,
 <tf.Tensor: shape=(), dtype=float32, numpy=4.486006>)

In [ ]:
1*224*224*3

150528

In [ ]:
#8.Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
tf.random.set_seed(32)
z= tf.constant(np.random.randint(1,50), shape=(1,224,224,3))
z



<tf.Tensor: shape=(1, 224, 224, 3), dtype=int32, numpy=
array([[[[3, 3, 3],
         [3, 3, 3],
         [3, 3, 3],
         ...,
         [3, 3, 3],
         [3, 3, 3],
         [3, 3, 3]],

        [[3, 3, 3],
         [3, 3, 3],
         [3, 3, 3],
         ...,
         [3, 3, 3],
         [3, 3, 3],
         [3, 3, 3]],

        [[3, 3, 3],
         [3, 3, 3],
         [3, 3, 3],
         ...,
         [3, 3, 3],
         [3, 3, 3],
         [3, 3, 3]],

        ...,

        [[3, 3, 3],
         [3, 3, 3],
         [3, 3, 3],
         ...,
         [3, 3, 3],
         [3, 3, 3],
         [3, 3, 3]],

        [[3, 3, 3],
         [3, 3, 3],
         [3, 3, 3],
         ...,
         [3, 3, 3],
         [3, 3, 3],
         [3, 3, 3]],

        [[3, 3, 3],
         [3, 3, 3],
         [3, 3, 3],
         ...,
         [3, 3, 3],
         [3, 3, 3],
         [3, 3, 3]]]], dtype=int32)>

In [ ]:
z_squeezed = tf.squeeze(z)
z_squeezed.shape, z_squeezed.ndim,z_squeezed


(TensorShape([224, 224, 3]),
 3,
 <tf.Tensor: shape=(224, 224, 3), dtype=int32, numpy=
 array([[[3, 3, 3],
         [3, 3, 3],
         [3, 3, 3],
         ...,
         [3, 3, 3],
         [3, 3, 3],
         [3, 3, 3]],
 
        [[3, 3, 3],
         [3, 3, 3],
         [3, 3, 3],
         ...,
         [3, 3, 3],
         [3, 3, 3],
         [3, 3, 3]],
 
        [[3, 3, 3],
         [3, 3, 3],
         [3, 3, 3],
         ...,
         [3, 3, 3],
         [3, 3, 3],
         [3, 3, 3]],
 
        ...,
 
        [[3, 3, 3],
         [3, 3, 3],
         [3, 3, 3],
         ...,
         [3, 3, 3],
         [3, 3, 3],
         [3, 3, 3]],
 
        [[3, 3, 3],
         [3, 3, 3],
         [3, 3, 3],
         ...,
         [3, 3, 3],
         [3, 3, 3],
         [3, 3, 3]],
 
        [[3, 3, 3],
         [3, 3, 3],
         [3, 3, 3],
         ...,
         [3, 3, 3],
         [3, 3, 3],
         [3, 3, 3]]], dtype=int32)>)

In [ ]:
#9.Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
index_value=tf.constant([1,2,3,4,5,6,7,8,9,10],dtype=tf.float32)
index_value
tf.argmax(index_value)

<tf.Tensor: shape=(), dtype=int64, numpy=9>

In [ ]:
#10.One-hot encode the tensor you created in 9.
tf.one_hot(z_squeezed,depth=3)


<tf.Tensor: shape=(224, 224, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        ...,

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        ...,

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0.